language: node_js
node_js:
- 8.11.3
- 10.6.0
deploy:
  provider: heroku
  email: alex@moonhighway.com
  skip_cleanup: true
  api_key:
    secure: LiN8wEpcferAVk3CH4XPN1Ran+cyu/MALz/l3bwa8JbN6Tjlh9xHaR+gO7SwdzpoNSofDAXBmD3lCVApTcQU78PuDe63cHZuFkPkVD4ipf0gdUSMaxeIZmOINJaGWStNCFXMHaGmyaLaZ5H4vYrMQDwuiBA7WJ9G2rco+RTcSPvJzNnHrr0PZdps53kfzNQrAGE3e4ol0atSiE1rymoQIT2IdsYLCFBY2LyAHTTGBwpCaA8pJGsI4z4LsKEMkHY9y4DAtHSPq4sK1i01KANH+yrHnsI+qHhTYa3pEKXGJJrL+vKQZo+GT3mYWTVPcZwoRl34k8GQAOrLIIVWEdD1m6VOdwHH2hGTDHU6VvmTPCdZDJNrG0wlIAtpsWIQRKEgFKRyAGXq/lSAZzYv+qD1hnAxWIH2aNX5KkW5NMrFmie6doyQDmKDh1vKqoTSQNW8jmTD5mF0yY1rg/8GbjJK+ANKE063BLjIFvf21/33kifiYVG0RRVHTo4U3VQvV386ur7UxFm88y+8Ok54mhPE2ebXxWUte/KikaqNSiQVuL7LgDznRMOnzdBVtsmPjahBWRXcOPU8FSN8ithBBEvHH/9/f36j07PYyD54FHFjQjlczh2cF6PFYhEodVBQV5GZACOtd0TTZPnQIzw/rNNZAObw6tqyhRvj6MBi0pRgqLc=
  app: clam-graphql-api
  on:
    repo: MoonHighway/clam-graphql-api
    branch: master
