language: node_js
node_js:
- 8.11.3
- 10.6.0
deploy:
  provider: heroku
  email: alex@moonhighway.com
  skip_cleanup: true
  api_key:
    secure: nXX+XYettlTik9jkqZQVZaJCuxfwF5dmIj5nCpe3aealvVETtQ8dr5RYb0WfQIEC3Kw6RloLC8uE0Cej4cttCWnf4xSbU4ohh2/iZBf6sW3wntB6zkxzmv4YBS0jaFwTG1hLRcL3zKEzQSxQL+ZIoMOgRU3wSVWOPyLoseK7+4A3sa4upwYWl/TCOpNQ9KMMl8+rGYIFwWYBOuBQet841ItB4AV+Kp6a0xCL/zn4RHoslOiVgFtj5SWP7tgG3E3McozukUO82GkrG8lnt0G/3aPlOzvjUIVmxlStepgHfEwrroaqI55z2YmtZ6s5SYDtVfCeNGHt9/N1+CRWW6zFZFydhinEChG/aHLV6H5EDX24dFb6+7BUxNT0DsO9y/jdIh5ClwRXmB+QQM2TbOp/Opx8xu+Ox9c6uAUq9yQVBgcFbDi8NpLb6C8G9+mPOGhsQMB7As6ETw3AXCqQFp9QHWlvtoBeoM3VgjedjdXoaH+W+1jchN2FgYWiajw7h8g58YWLu6SRvkxm7NnFU6E74DPI3WLrAVEf9ngaWlGhX6Yli04VxsMRCG+MA4I0MGawt8/pam3BTtAgcGmfnFChAEYHNYb77I3Mw4Js8n/xvwMYtxeVAvRvdpKGQscQjlMqVfnZ25JPn5+UNYmbsl8RDRMOJyjY9NtSPektG39iNwA=
  app: clam-graphql-api
  on:
    repo: MoonHighway/clam-graphql-api
    branch: master
