language: node_js
node_js:
- 8.11.3
- 10.6.0
deploy:
  provider: heroku
  api_key:
    secure: saAc5ZFa+yS8/P0jKSKtFc1cUSt16HmnsLxyUGS0xcNH1/f96gVGnC/T/7ug3mpGAMKTkLweu7uMkr0vajc1JJTQmJkdAKXpM3fbTNTHGm/6xVZxW6aREhOozIdOmGBSZyaZs3N17mhWKbqOdYHaGK5il6nOtE4huw5TvcwHcm56KeoGWLSOXSAJ2Oq71AR3a+WRXAosFCeTi8fUjrJ20Frbg2l5ToegFgRHDYQZZGalFOp3iOhfTLmN3Rp69JVytYO1hbyRp7Mr1osx6xYn5IRVlUPgNh+wA9NzppGhOLutZH16q1m7irqLAvq7tp1tUMv/21LoHSgmtJ75Ayj5RPT+rVOJSCk+ZbEHEmTozPqf86GFRCeyhoFMFd5qYP5ntXJSizZ6ophBOyRLvcYoB40egM+Gu6yCA+e+E77KFVb6FzVzrMFEDO07an/5MuVpraPx1d7NVPUHJxdwNlypez0/BU3LmH3Fcq0Qk6H6A8dJbQEdqG0p8xY6f1OBHim9oyBPoajiNgkvgUrgj3dVrMbllz3Xgh3OlUG/EgYHHZ5YLpAob3S3iIkFE9qRPH3nQSVskFbul8+dkTWJu3PjUD20d8bY13mVJMWVC6shwMUWb3lbj5TN/dZpQ0MJTIh77EvpYo3BQ2WAE9aodagk1cmxIAZTrQnsPmGCpsJ0Kp4=
  app: clam-graphql-api
  on:
    repo: MoonHighway/clam-graphql-api
