language: node_js
node_js:
  - 8.11.3
  - 10.6.0
env: 
  - "NODE_ENV=test"  
before_script:
  - npm run build
  - npm start &
after_script:
  - npm install -g apollo
  - apollo schema:check --endpoint http://localhost:4000   
after_deploy: 
  - npm run build
  - npm start &
  - npm install -g apollo
  - apollo schema:publish --endpoint http://localhost:4000
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: MZ0GOXgDXHkHFqxRIoVjcxGkE0NOCY63CuCfa95iTmWvqNYILYUWS8oMd09bxr8MHyYl2uE0R//pSu2oaYSBvP+DitjwODsR7No5nHCfO/VVrAwXUS0aUA78ACcJLRUcYYwYbxM3HP/+0P7PpncVG0pcGCx4oZGHaLyJlBlkBxF/y+8SAjy8wMOqu1Oi6tMEwqLyvQ9fpYpWRPcAU2e8tVMis0kzw0RsfQGcvVoj1Eos3cAPpZsH4Jvdrsa2N9lN8QIJgacEMif79asv/UKhhz0t0RZ7uZSnwBiM29O16QL9oFVthYBxbEXv9oRd1MpLGH3by5UcrgnB9ASkINz/D7/W54YTzn3sROooREFGYj8KKBJ94w1IuGdaCuVn3DH2dNdGd2DjDFgwYCsqmQ7Kh/KuP877dnq9ysE9Vhj/ZYNTFFu11nnNw212ZespCJ/dsfK3EFRl55/LMtYLbCdlqfYgdC5mMk28aX4fKrm+U8RJ0qOGk5QOaAWJpCQnnvTIj/EzhEwQ2ps50lgQrxKYWhK6HKK41HQhnDIPj9yuKw40KJvw3yA1rUD2YznFq+NQ3DAOcOMz+akCGMMHc6CJzq5qNg68Ga7qtx/7iTR1OlbZ2dfpqFKQJHHb6tJ9kbg+oX3Miu/AnebyofqhBALAf3NB9K9cIfkB8Ls7pE9Co3s=
  app: clam-graphql-api
  on:
    repo: MoonHighway/clam-graphql-api
